### PR TITLE
Use HTTPS for Hero Patterns Website

### PR DESCRIPTION
**Pull request by vikas5914**

### CODE REVIEW

**Comment by simonswiss** [comment]
Thanks for that 👍

**Comment by adamwathan** [comment]
Hero Patterns currently is not deployed with SSL so this link is just broken, please test changes like this :/

**Comment by vikas5914** [comment]
@adamwathan I tested it and still working.  

Check this: https://www.sslshopper.com/ssl-checker.html#hostname=https://www.heropatterns.com/

image

image

**Comment by adamwathan** [comment]
Ah weird, I guess it's just not available without `www`. Sorry for the mix up, will revert the reverted change, thanks.

**Pull request merged**
