### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by foucist**
Increase browser support from 85% to 90% coverage

> npx browserslist --coverage "> 1%"
> These browsers account for 85.27% of all users globally
> npx browserslist --coverage "> 0.5%"
> These browsers account for 90.21% of all users globally

### CODE REVIEW

**Comment by foucist** [comment]
Based on the preview app produced by the CI, the change doesn't fix the bug I'm encountering in Safari 13.1.

v3 site refuses to display properly.  It throws a next js client side error message and a bunch of these types of messages:

`[Error] TypeError: b.addEventListener is not a function. (In 'b.addEventListener("change",S)', 'b.addEventListener' is undefined)`

Any ideas on source of error?

**Comment by reinink** [comment]
Hey thanks for reporting this bug! I was able to reproduce to this and fix it: 6024007d1578e14109509a154b89661762064914 👍

**Comment by foucist** [comment]
interesting, so it was due to using addEventListener instead of addListener which is deprecated

**Comment by reinink** [comment]
Yeah, Safari 13 doesn't have support for the new `addEventListener` method, so we had to detect that and use the older `addListener` method instead.

**Pull request closed without merging**
