### PR TITLE
fix: added example to theme extend paragraph

### PR DESCRIPTION
**Pull request by DavideFrancescon**
Closes: #1571 

Result in the docs:

Screenshot 2023-08-22 alle 16 32 01

Result of the code in the example:

Screenshot 2023-08-22 alle 16 30 26

### CODE REVIEW

**Comment by thecrypticace** [comment]
@DavideFrancescon Can you enable maintainer editing for this PR in the right sidebar at the bottom?

**Comment by DavideFrancescon** [comment]
> @DavideFrancescon Can you enable maintainer editing for this PR in the right sidebar at the bottom?

Let me know if it's okay now, I don't have the button you are talking about or the button in the guide from github. I searched a bit in the repo and I think I found the right setting, hopefully

**Comment by thecrypticace** [comment]
Nah, that didn't work. I'll re-create the PR and add you as a co-author to the commit. No worries.

**Comment by thecrypticace** [comment]
Opened a new PR: #1669

**Pull request closed without merging**
