### PR TITLE
Fix typo in BuildAnything.js

### PR DESCRIPTION
**Pull request by cmdecker95**
From "Classic Utility Jacket" to "Utility Jacket" to match the figure displayed above it.

image

### CODE REVIEW

**Comment by cmdecker95** [comment]
Hmm, the preview reveals that I didn't fix it. Let me try to find the source of that string!

**Comment by cmdecker95** [comment]
Found it (see [my latest commit](https://github.com/tailwindlabs/tailwindcss.com/commit/df153438d8a6b9a9df51a31cb074b23ad673a4b3))

**Comment by cmdecker95** [comment]
Fix confirmed! Ready to merge ✅image

**Comment by adamwathan** [comment]
Thanks!

**Pull request merged**
