### PR TITLE
Update installation.mdx

### PR DESCRIPTION
**Pull request by Rolanddoda**
Install as devDependencies

### CODE REVIEW

**Comment by adamwathan** [comment]
Can you explain the motivation behind this change? Is it just personal preference or are there objective reasons to do this? We personally install these as regular dependencies in our projects (including the Tailwind website itself).

**Comment by Rolanddoda** [comment]
Hi @adamwathan, thanks for the quick reply.

I think that those are "Packages that are only needed for local development".
Also, as I can see in [Laravel guide](https://tailwindcss.com/docs/guides/laravel) and in [Vue 3 guide](https://tailwindcss.com/docs/guides/vue-3-vite) the commands use **-D** for setting up Tailwind CSS.
So at least for consistency, if not the "Packages that are only needed for local development" is not a good argument, I think it's better to install them as devDependencies.

*This is my first contribution to TailwindCSS and in I want to thank you and the team for this awesome project.*

**Comment by adamwathan** [comment]
Thanks for the kind words! ❤️ 

Yeah so the tricky thing about how we build projects these days is that technically _everything_ is only used for local development, since we compile a production build that's a totally separate artifact using webpack or similar. So generally I put everything needed to produce the production build in `dependencies` and use `devDependencies` for things that are really only needed for development, like test-runners, linters, etc.

Since `devDependencies` are often not installed in CI for example, putting things there instead of in `dependencies` that are needed to produce the build can cause your builds to fail in CI.

I'm open to changing it if there's a compelling reason for sure but I think there are pros and cons to both so it's tough.

**Comment by Rolanddoda** [comment]
Hmm, I am not an expert of course, but I think `devDependencies` actually run in CI. AFAIK in CI you can run commands for running test (which are devDependencies), linters (devDependencies) etc.
For example in my project I've setup CI with Github actions to run tests, and also to build code (devDependencies eg vue-cli-service) for CD.

Also, if you think that it's better to use `dependencies` instead of `devDependencies` I think the other examples (Laravel, Vue 3 etc) should use a consistent way of installing/setting-up tailwind.

Personally I like to differentiate dependencies and devDependencies by:

- dependencies (packages which gets included in the bundled code)
- devDependencies (packages which are used as tools for development and not included in the bundled code)

postcss, autoprefixer, tailwindcss are tools which *do things* on your code, but their code it's not included in the bundled application code.

---------------------

However, I am not insisting to do what I recommend, at the end I might be wrong.

Feel free to close this PR and don't think too much about it.

*I'm still learning tailwindCSS and I will try to contribute whenever I find the time/I can because I'am amazed so far. With respect, Roland.*

**Comment by adamwathan** [comment]
Going to merge this, I think I've changed my stance on this now and the consensus when I ran a poll on Twitter was that people generally like to use `dependencies` only for things that actually end up in the bundle and are served to the client 👍🏻 

https://twitter.com/adamwathan/status/1358487239181877249

Thanks for the change!

**Comment by Rolanddoda** [comment]
Thanks for merging this @adamwathan. :) OMG my first contribution 😲. (more to come, hopefullly).
I know that this is not the appropriate place to ask but I've asked in your Youtube channel but didn't get response:

- Is there any info you want to share about the re-recorded version of designing with TailwindCSS ?
- How can I sponsor you ? I see that I can't sponsor you in Github.
- Is there any place that someone can keep up with tailwindCSS (blog, videos, tips, newsletter) ?
- Is the any paid course for tailwindCSS ? I see that screencasts are free and almost anything is free if you want to learn tailwindCSS, but I would pay for a course with Vue and TailwindCSS not only to learn tailwind, because it's really easy to learn it and find anything in the docs, but to learn best practices, tips and advanced usage and scenarios.
- Is there any way someone can DM you ? I wanted to ask these questions via DM but couldn't do it on twitter.

Finally I want to thank you for [THIS AMAZING FREE COURSE](https://www.youtube.com/watch?v=21HuwjmuS7A&list=PL7CcGwsqRpSM3w9BT_21tUU8JN2SnyckR&index=1). I didn't only learned tailwindCSS but also some nice Vue tricks, design, CSS tricks and in general, I think it's a must watch course for everyone. THANK YOU.

Sorry for the long comment and for asking those questions here 🙂

**Pull request merged**
