### PR TITLE
Add Symfony framework guide

### PR DESCRIPTION
**Pull request by AmProsius**
I added a Symfony framework guide similar to the Laravel one. You can find a working repository of this guide [here](https://github.com/AmProsius/symfony-tailwind). I created that repository as a temporary solution and will probably remove it if this guide will be merged.

### CODE REVIEW

**Comment by AmProsius** [comment]
@thecrypticace I noticed that the other framework guides were already merged and this one wasn't. Everything alright with this guide or is there something for me to improve?

**Comment by reinink** [comment]
@AmProsius Hey! Thanks for submitting this framework guide. We had planned all the other guides at the start of our current work cycle, which is why they were finalized and merged in. We've also tried to implement these in threes, so that the layout on the [framework guides](https://tailwindcss.com/docs/installation/framework-guides) page looks nice 😅

We'll certainly consider this for a future update though 👍

**Comment by AmProsius** [comment]
> We've also tried to implement these in threes, so that the layout on the [framework guides](https://tailwindcss.com/docs/installation/framework-guides) page looks nice 😅

That makes absolute sense. Thanks for the insight and I'm looking forward to this guide getting merged in the future.

**Review by ArnaudLier — APPROVED** [review]

**Comment by thecrypticace** [comment]
whoops… didn't meant to do that

**Pull request merged**
