### PR TITLE
add forms plugin page

### PR DESCRIPTION
**Pull request by ArielMejiaDev**
Instead of a link to `tailwindlabs/forms` repo, it adds a docs page like `typography` docs page.

### CODE REVIEW

**Comment by ArielMejiaDev** [comment]
Please consider adding this PR to the official Docs page.

**Comment by ArielMejiaDev** [comment]
Following this PR, if there are some required changes please let me know @adamwathan

**Comment by reinink** [comment]
Hey @ArielMejiaDev! Thanks for this contribution, but we've discussed this internally and have decided that, at least for now, we'd prefer to keep the plugin documentation in the README files of their respective Git repositories.

I've actually gone ahead and moved the typography plugin docs back to the README and removed that page from the docs (6d5a944f70ba8749bb0f3fc10d8186f8a5fc176f).

Definitely appreciate your efforts here either way — your implementation here was solid, but given this new direction I am going to close this PR. Hope that makes sense! 🤙

**Comment by ArielMejiaDev** [comment]
@reinink thanks, appreciate your comment, please let me know if there are some issues related to docs, I want to give back something for all the value that TailwindCSS provides, 

Also, did you consider to add a link to the form plugin read me file in TailwindUI docs?


This could make sense, because some inputs like checkboxes needs the plugin to get the same look and feel.

Thanks for all the hard work of the Tailwind team.

**Pull request closed without merging**
