### PR TITLE
Added Qwik to the framework guide section

### PR DESCRIPTION
**Pull request by zanettin**
Added [Qwik](https://qwik.builder.io) to the [Framework Guide](https://tailwindcss.com/docs/installation/framework-guides) section of the docs.

Detailed steps to validate can be found as well on the [Qwik docs](https://qwik.builder.io/docs/integrations/tailwind/).

Thank you very much for considering this PR 🙏

PS: this PR also contains some adjustments which `npm run format` detected 😄

### CODE REVIEW

**Comment by manucorporat** [comment]
Looking great!!

**Comment by zanettin** [comment]
Hi @adamwathan 👋 
Sorry to ping you directly, but I just wanted to ask if there's anything else I can do to increase the chances of getting this pull request considered for merging. 👼 have a great day

**Comment by reinink** [comment]
Hey thanks for submitting this contribution!

I've made some tweaks to the guide to have it match the format of our other guides a little better. We generally prefer to show more detailed instructions in our guides on how to setup Tailwind CSS over using a tool specific command like `npm run qwik add tailwind`. Not that there is anything wrong with having a command like that available, but we loose the opportunity to teach what's all involved in getting Tailwind setup in a project. Hope that makes sense!

I've also reverted the code formatting changes and will add those in a subsequent commit.

Thanks again! 🤙

**Comment by zanettin** [comment]
thx a lot @reinink for your time and the adjustments 🙏

**Pull request merged**
