### PR TITLE
Add jsx to purge

### PR DESCRIPTION
**Pull request by jonasdev**
Will solve the issue I had https://github.com/tailwindlabs/tailwindcss.com/issues/666

### CODE REVIEW

**Comment by bradlc** [comment]
Hey thanks @jonasdev! I think we should update this for sure. If you don't mind please could you update it to be a single glob, and add `ts` and `tsx` as well? If it can match the glob in the [Gatsby guide](https://github.com/tailwindlabs/tailwindcss.com/blob/master/src/pages/docs/guides/gatsby.mdx) that would be perfect 👍

**Comment by jonasdev** [comment]
@bradlc Sure. Good idea. Didn't catch the glob in first commit, which caused another commit, my bad. It should be working now

**Comment by bradlc** [comment]
Thanks! Sorry to be a pain, can we make this a single item? i.e. `./src/**/*.{js,jsx,ts,tsx}`

**Comment by jonasdev** [comment]
Just the way you want 👌

**Comment by bradlc** [comment]
Perfect, thank you! 🙌

**Pull request merged**
